### ISSUE TITLE
README.me must be extended

### ISSUE THREAD

**Issue by msamoylov** [bitmazk/cmsplugin-image-gallery#10]
Can you please extend the README file. It's incomplete now and `./manage.py migrate` is crashing. 
It should be:

Add easy_thumbnails, filer and image_gallery to your INSTALLED_APPS:

```
INSTALLED_APPS = (
    ...,
    'easy_thumbnails',
    'filer',
    'image_gallery',
)
```

**Comment by Tyrdall** [comment]
Done!
