### ISSUE TITLE
How to add pagination

### ISSUE THREAD

**Issue by vaibhav-jain** [bitmazk/cmsplugin-image-gallery#11]
Hi,

How to add pagination to gallery like [this](http://haintheme.com/demo/html/kinder/gallery.html#)

_PS: Thanks for the awesome plugin :+1:_ 

Thanks,
Vaibhav

**Comment by Tyrdall** [comment]
Hi @vaibhav-jain we already use pagination in the gallery list view: https://github.com/bitmazk/cmsplugin-image-gallery/blob/master/image_gallery/views.py#L10

Paginating images is not provided at the moment. You could search for a js plugin to display the gallery with a pagination feature, for example.

If you want to add something to this repository, feel free to send a pull request. Thanks! :)
