### ISSUE TITLE
What is the difference between Teaser and Default?

### ISSUE THREAD

**Issue by bethlakshmi** [bitmazk/cmsplugin-image-gallery#5]
I just pip installed this plugin and there is no difference between teaser and default that I can see.  I don't mind if there is no CSS for it... my problem is that there is no obvious difference, either on the page or in the HTML.  So... what is the point of the display type if it does nothing?

If it could just show up as a class in the HTML, I could easily use it to build up CSS to change the display...

**Comment by Tyrdall** [comment]
Well, you are able to create a custom template to use different types of galleries in your project. You can add the display type as a css class and create some styles or even use it in an if clause to enable/disable other contents. It's up to you =)

**Comment by bethlakshmi** [comment]
My point was that I was looking in the HTML that you create and there are no hooks that say "default" or "teaser" in that HTML.  To do what you describe, I would have SOMETHING in the HTML - like class="default" tag that would let me hook CSS to it.

All that the code you provide does is:
<h1>{{ gallery.title }}</h1>
<h2>{% if gallery.date %}{{ gallery.date|date }}, {% endif %}{{ gallery.location }}</h2>
<p>{% render_placeholder gallery.description "description" %}</p>
<ul class="imageGallery">
    {% for image in gallery.get_folder_images %}
        <li><img src="{% thumbnail image.file 200x200 crop upscale %}" alt=""></li>
    {% endfor %}
</ul>

Which means that other than the class="Image Gallery" there is nothing to distinguish your output and there is no way to identify whether my plugin setting are using "teaser" or "default"

I offer as a counter example, this:

https://github.com/bethlakshmi/cmsplugin-image-gallery/blob/master/image_gallery/templates/image_gallery/partials/gallery.html

which actually puts the display_type into the output so it can be used in some meaningful way.

I asked in case I was missing the specific way you implemented this, but you haven't provided me with any details on how I could write CSS that would actually work....

**Comment by Tyrdall** [comment]
Alright, added it to the template. https://github.com/bitmazk/cmsplugin-image-gallery/commit/ab2dedcbdc42436aafdc45582a1e771cb82ea7a0
