### ISSUE TITLE
placeholder_tags / cms_tags

### ISSUE THREAD

**Issue by spout** [bitmazk/cmsplugin-image-gallery#7]
Using django-cms==3.1.2
Couldn't load placeholder_tags in image_gallery/templates/image_gallery/partials/gallery.html

As seen in this issue:
@bethlakshmi forked it and corrected the template tag load: https://github.com/bethlakshmi/cmsplugin-image-gallery/commit/d31a138c22e44a4ef4592405b28b5b489e98f7ba

@bethlakshmi are you planning pull request here to fix this on PyPI ?

**Comment by Tyrdall** [comment]
@spout https://github.com/bitmazk/cmsplugin-image-gallery/commit/d2a77f7251b99dbf8b2262031e8dd4074cbe86a4
https://github.com/bitmazk/cmsplugin-image-gallery/commit/819bb9dd08ddd72659e69c8b0ed801f2cb2a1a1d

Anything else to change?

**Comment by spout** [comment]
Don't see anything else.
Thank you for quick reply !

**Comment by Tyrdall** [comment]
@spout Can you test it using your setup? After testing I can create a new release.

**Comment by spout** [comment]
Unit tests ? I've nothing that use gallery_list.html can't test by myself.

**Comment by Tyrdall** [comment]
I assume you got a setup containing django-cms==3.1.2. Can you simply test the templates in your browser.

**Comment by spout** [comment]
It's OK for the gallery.html fix, but I don't find in which case gallery_list.html is used.

**Comment by Tyrdall** [comment]
It's only used with the apphook: https://github.com/bitmazk/cmsplugin-image-gallery/blob/master/image_gallery/cms_app.py

https://pypi.python.org/pypi/cmsplugin-image-gallery/0.7.1

**Comment by spout** [comment]
Updated pip package to 0.7.1. Thank you.
